server:
  port: 8088
  error:
    include-message: always
    include-binding-errors: always

spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://ep-hidden-dew-annaq7wt-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: "npg_vQzxhjDuq2i6"
    driver-class-name: org.postgresql.Driver

    ##############################
    hikari:
      max-lifetime: 600000
      idle-timeout: 300000
      minimum-idle: 2
      maximum-pool-size: 10
      keepalive-time: 30000
      connection-timeout: 30000
      validation-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 465
    username: jomap.system@gmail.com
    password: "cesompzbwfmoukmu"
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000

  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

app:
  google:
    client-id: 712232187160-k5t0nf7vmqc1muap0vc1bj3h4shl4niu.apps.googleusercontent.com

  facebook:
    app-id: 26700675972951501
    app-secret: 96312ae0d443ae022cd008afc12bc380
gemini:
  api:
    key: ${GEMINI_API_KEY}
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash:generateContent
