server:
  port: 8088
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:postgresql://ep-hidden-dew-annaq7wt-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: "npg_vQzxhjDuq2i6"
    driver-class-name: org.postgresql.Driver

    ##############################
    hikari:
      max-lifetime: 600000
      idle-timeout: 300000
      minimum-idle: 2
      maximum-pool-size: 10
      keepalive-time: 30000
      connection-timeout: 30000
      validation-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 465
    username: jomap.noreply@gmail.com
    password: wygkpqjrrfjbmfed
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000

  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

app:
    google:
      client-id: 819033309831-c9n98js1qev5o49nnovpo3f2vn8h8e6m.apps.googleusercontent.com

    facebook:
      app-id: 26700675972951501
      app-secret: 96312ae0d443ae022cd008afc12bc380
